-- ==============================================================
-- V1: ベースライン(後追い化)
--
-- これまでこのアプリは spring.jpa.hibernate.ddl-auto=update により、
-- Entityの変更に合わせてHibernateが自動的にテーブルを作成・更新してきた
-- (マイグレーションファイル・バージョン管理の仕組みは存在しなかった)。
--
-- このファイルは、2026-08-29時点で実際に稼働しているPostgreSQL(kinn_db)の
-- スキーマを pg_dump --schema-only でそのまま書き起こしたものである
-- (手打ちでEntityから起こしたDDLではなく、実物からの書き起こしのため、
-- CommandLineRunner群(CompanyCodeMigrationRunner等)が起動時に動的に
-- 修正してきたCHECK制約・列幅なども含め、現物と完全に一致している)。
--
-- spring.flyway.baseline-on-migrate=true を設定しているため、既にこのスキーマが
-- 存在する既存DB(本番・各自のローカル開発DB)に対しては、このV1は実際には
-- 実行されず「バージョン1の状態まで完了済み」として記録されるだけになる
-- (baseline化)。一方、まだテーブルが存在しない新しいDB(CIやチームメンバーの
-- 新規セットアップ等)に対しては、このV1がそのまま実行され、既存環境と同じ
-- スキーマが作られる。
--
-- 以後のテーブル変更は、Entityの変更だけでなく、対応する
-- V{番号}__説明.sql を db/migration に追加する形で行うこと(README.md参照)。
-- pg_dump時点で不要になっている過去機能のテーブル(notification_settings,
-- password_reset_token)も、実際に稼働中のDBに存在する以上はそのまま含めている
-- (削除する場合も、このファイルを書き換えるのではなく新しいマイグレーション
-- (例: V2__drop_notification_settings.sql)として追加すること)。
-- ==============================================================

--
-- Name: account_security_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.account_security_log (
    id bigint NOT NULL,
    action_type character varying(64) NOT NULL,
    occurred_at timestamp(6) without time zone NOT NULL,
    performed_by_employee_id character varying(64),
    performed_by_name character varying(100),
    target_employee_id character varying(64) NOT NULL,
    target_name character varying(100)
);


--
-- Name: account_security_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.account_security_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_security_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ai_meal_suggestion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ai_meal_suggestion (
    id bigint NOT NULL,
    attempt_no integer NOT NULL,
    based_on_date date,
    created_at timestamp(6) without time zone,
    employee_id character varying(64) NOT NULL,
    is_saved boolean NOT NULL,
    source character varying(32) NOT NULL,
    suggestion_date date NOT NULL,
    summary_note character varying(500),
    CONSTRAINT ai_meal_suggestion_source_check CHECK (((source)::text = ANY ((ARRAY['AI'::character varying, 'RULE_BASED'::character varying])::text[])))
);


--
-- Name: ai_meal_suggestion_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ai_meal_suggestion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_meal_suggestion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ai_meal_suggestion_item; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ai_meal_suggestion_item (
    id bigint NOT NULL,
    calories integer,
    carbs_g double precision,
    cooking_minutes integer,
    dish_name character varying(200),
    fat_g double precision,
    ingredients character varying(500),
    meal_type character varying(32) NOT NULL,
    protein_g double precision,
    reason character varying(1000),
    suggestion_id bigint NOT NULL,
    CONSTRAINT ai_meal_suggestion_item_meal_type_check CHECK (((meal_type)::text = ANY ((ARRAY['BREAKFAST'::character varying, 'LUNCH'::character varying, 'DINNER'::character varying, 'SNACK'::character varying])::text[])))
);


--
-- Name: ai_meal_suggestion_item_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ai_meal_suggestion_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_meal_suggestion_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_user (
    id bigint NOT NULL,
    company_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    full_name character varying(100) NOT NULL,
    login_id character varying(64) NOT NULL,
    password_hash character varying(100) NOT NULL,
    role character varying(32) NOT NULL,
    department character varying(100),
    "position" character varying(100),
    department_id bigint,
    enabled boolean DEFAULT true NOT NULL,
    failed_login_attempts integer DEFAULT 0 NOT NULL,
    locked_until timestamp(6) without time zone,
    last_login_at timestamp(6) without time zone,
    must_change_password boolean DEFAULT false NOT NULL,
    email character varying(255),
    mfa_enabled boolean DEFAULT false NOT NULL,
    mfa_secret_encrypted character varying(500),
    CONSTRAINT app_user_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[])))
);


--
-- Name: app_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attendance_audit; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attendance_audit (
    id bigint NOT NULL,
    edited_at timestamp(6) without time zone NOT NULL,
    edited_by_employee_id character varying(64) NOT NULL,
    edited_by_name character varying(100),
    new_break_minutes integer,
    new_day_type character varying(32),
    new_end_time time(6) without time zone,
    new_start_time time(6) without time zone,
    previous_break_minutes integer,
    previous_day_type character varying(32),
    previous_end_time time(6) without time zone,
    previous_start_time time(6) without time zone,
    target_employee_id character varying(64) NOT NULL,
    work_date date NOT NULL,
    CONSTRAINT attendance_audit_new_day_type_check CHECK (((new_day_type)::text = ANY ((ARRAY['NORMAL'::character varying, 'SCHEDULED_HOLIDAY'::character varying, 'STATUTORY_HOLIDAY'::character varying, 'PAID_LEAVE'::character varying, 'SUBSTITUTE_HOLIDAY'::character varying, 'COMPENSATORY_HOLIDAY'::character varying, 'ABSENCE'::character varying])::text[]))),
    CONSTRAINT attendance_audit_previous_day_type_check CHECK (((previous_day_type)::text = ANY ((ARRAY['NORMAL'::character varying, 'SCHEDULED_HOLIDAY'::character varying, 'STATUTORY_HOLIDAY'::character varying, 'PAID_LEAVE'::character varying, 'SUBSTITUTE_HOLIDAY'::character varying, 'COMPENSATORY_HOLIDAY'::character varying, 'ABSENCE'::character varying])::text[])))
);


--
-- Name: attendance_audit_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.attendance_audit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attendance_audit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attendance_record; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attendance_record (
    id bigint NOT NULL,
    break_minutes integer,
    day_type character varying(32) NOT NULL,
    employee_id character varying(64) NOT NULL,
    end_time time(6) without time zone,
    late_or_early boolean,
    paid_leave_unit double precision,
    remarks character varying(255),
    start_time time(6) without time zone,
    work_date date NOT NULL,
    break_end_time time(6) without time zone,
    break_start_time time(6) without time zone,
    auto_break_minutes integer,
    CONSTRAINT attendance_record_day_type_check CHECK (((day_type)::text = ANY ((ARRAY['NORMAL'::character varying, 'SCHEDULED_HOLIDAY'::character varying, 'STATUTORY_HOLIDAY'::character varying, 'PAID_LEAVE'::character varying, 'SUBSTITUTE_HOLIDAY'::character varying, 'COMPENSATORY_HOLIDAY'::character varying, 'ABSENCE'::character varying])::text[])))
);


--
-- Name: attendance_record_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.attendance_record ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attendance_record_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: company; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.company (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    name character varying(100) NOT NULL,
    company_code character varying(12)
);


--
-- Name: company_holiday_rule; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.company_holiday_rule (
    id bigint NOT NULL,
    company_code character varying(64) NOT NULL,
    saturday_day_type character varying(32) NOT NULL,
    sunday_day_type character varying(32) NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT company_holiday_rule_saturday_day_type_check CHECK (((saturday_day_type)::text = ANY ((ARRAY['NORMAL'::character varying, 'SCHEDULED_HOLIDAY'::character varying, 'STATUTORY_HOLIDAY'::character varying, 'PAID_LEAVE'::character varying, 'SUBSTITUTE_HOLIDAY'::character varying, 'COMPENSATORY_HOLIDAY'::character varying, 'ABSENCE'::character varying])::text[]))),
    CONSTRAINT company_holiday_rule_sunday_day_type_check CHECK (((sunday_day_type)::text = ANY ((ARRAY['NORMAL'::character varying, 'SCHEDULED_HOLIDAY'::character varying, 'STATUTORY_HOLIDAY'::character varying, 'PAID_LEAVE'::character varying, 'SUBSTITUTE_HOLIDAY'::character varying, 'COMPENSATORY_HOLIDAY'::character varying, 'ABSENCE'::character varying])::text[])))
);


--
-- Name: company_holiday_rule_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.company_holiday_rule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.company_holiday_rule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: company_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.company ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.company_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: department; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.department (
    id bigint NOT NULL,
    company_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    name character varying(100) NOT NULL
);


--
-- Name: department_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.department ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.department_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: health_alert; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.health_alert (
    id bigint NOT NULL,
    alert_type character varying(32) NOT NULL,
    created_at timestamp(6) without time zone,
    employee_id character varying(64) NOT NULL,
    message character varying(500) NOT NULL,
    severity character varying(16) NOT NULL,
    triggered_date date NOT NULL,
    CONSTRAINT health_alert_alert_type_check CHECK (((alert_type)::text = ANY ((ARRAY['LOW_SLEEP'::character varying, 'HIGH_FATIGUE'::character varying, 'HIGH_STRESS'::character varying, 'HIGH_OVERTIME'::character varying])::text[]))),
    CONSTRAINT health_alert_severity_check CHECK (((severity)::text = ANY ((ARRAY['INFO'::character varying, 'WARNING'::character varying])::text[])))
);


--
-- Name: health_alert_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.health_alert ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.health_alert_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: health_audit_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.health_audit_log (
    id bigint NOT NULL,
    action character varying(16) NOT NULL,
    actor_employee_id character varying(64) NOT NULL,
    actor_name character varying(100),
    company_id bigint NOT NULL,
    error_message character varying(255),
    ip_address character varying(64),
    occurred_at timestamp(6) without time zone NOT NULL,
    resource character varying(32) NOT NULL,
    result character varying(16) NOT NULL,
    target_employee_id character varying(64),
    target_name character varying(100),
    target_ref character varying(255),
    user_agent character varying(512),
    CONSTRAINT health_audit_log_action_check CHECK (((action)::text = ANY ((ARRAY['VIEW'::character varying, 'CREATE'::character varying, 'UPDATE'::character varying, 'DELETE'::character varying])::text[]))),
    CONSTRAINT health_audit_log_resource_check CHECK (((resource)::text = ANY ((ARRAY['PROFILE'::character varying, 'DAILY_CHECK'::character varying, 'HISTORY'::character varying, 'SCORE'::character varying, 'TREND'::character varying, 'ALERT'::character varying, 'ANALYSIS'::character varying, 'MONTHLY_RECORD'::character varying, 'ADMIN_DASHBOARD'::character varying, 'AUDIT_LOG'::character varying])::text[]))),
    CONSTRAINT health_audit_log_result_check CHECK (((result)::text = ANY ((ARRAY['SUCCESS'::character varying, 'DENIED'::character varying, 'FAILURE'::character varying])::text[])))
);


--
-- Name: health_audit_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.health_audit_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.health_audit_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: health_check; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.health_check (
    id bigint NOT NULL,
    body_temperature double precision,
    check_date date NOT NULL,
    condition_level character varying(32),
    created_at timestamp(6) without time zone,
    employee_id character varying(64) NOT NULL,
    exercise_minutes integer,
    fatigue_level integer,
    memo character varying(500),
    sleep_hours double precision,
    stress_level integer,
    updated_at timestamp(6) without time zone,
    CONSTRAINT health_check_condition_level_check CHECK (((condition_level)::text = ANY ((ARRAY['GREAT'::character varying, 'GOOD'::character varying, 'NORMAL'::character varying, 'SLIGHTLY_BAD'::character varying, 'BAD'::character varying])::text[])))
);


--
-- Name: health_check_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.health_check ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.health_check_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: health_profile; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.health_profile (
    id bigint NOT NULL,
    avg_sleep_hours double precision,
    body_temperature double precision,
    department character varying(64),
    diastolic_bp integer,
    drinking_status character varying(32),
    employee_id character varying(64) NOT NULL,
    exercise_minutes integer,
    health_memo character varying(1000),
    height_cm double precision,
    smoking_status character varying(32),
    stress_level integer,
    systolic_bp integer,
    updated_at timestamp(6) without time zone,
    weight_kg double precision,
    CONSTRAINT health_profile_drinking_status_check CHECK (((drinking_status)::text = ANY ((ARRAY['NONE'::character varying, 'OCCASIONALLY'::character varying, 'REGULARLY'::character varying])::text[]))),
    CONSTRAINT health_profile_smoking_status_check CHECK (((smoking_status)::text = ANY ((ARRAY['NONE'::character varying, 'QUIT'::character varying, 'SMOKER'::character varying])::text[])))
);


--
-- Name: health_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.health_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.health_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: health_record; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.health_record (
    id bigint NOT NULL,
    condition character varying(32),
    diastolic_bp integer,
    employee_id character varying(64) NOT NULL,
    exercise_minutes integer,
    memo character varying(255),
    record_date date NOT NULL,
    sleep_hours double precision,
    steps integer,
    systolic_bp integer,
    weight_kg double precision,
    CONSTRAINT health_record_condition_check CHECK (((condition)::text = ANY ((ARRAY['GREAT'::character varying, 'GOOD'::character varying, 'NORMAL'::character varying, 'BAD'::character varying])::text[])))
);


--
-- Name: health_record_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.health_record ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.health_record_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: holiday_override; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.holiday_override (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    holiday_date date NOT NULL,
    is_holiday boolean NOT NULL,
    name character varying(100)
);


--
-- Name: holiday_override_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.holiday_override ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.holiday_override_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: meal_record; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.meal_record (
    id bigint NOT NULL,
    amount character varying(200),
    calories integer,
    carbs_g double precision,
    created_at timestamp(6) without time zone,
    dish_name character varying(200),
    employee_id character varying(64) NOT NULL,
    fat_g double precision,
    fiber_g double precision,
    items character varying(1000),
    meal_date date NOT NULL,
    meal_time time(6) without time zone,
    meal_type character varying(32) NOT NULL,
    memo character varying(500),
    photo_url character varying(500),
    protein_g double precision,
    salt_g double precision,
    updated_at timestamp(6) without time zone,
    recipe_id bigint,
    CONSTRAINT meal_record_meal_type_check CHECK (((meal_type)::text = ANY ((ARRAY['BREAKFAST'::character varying, 'LUNCH'::character varying, 'DINNER'::character varying, 'SNACK'::character varying])::text[])))
);


--
-- Name: meal_record_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.meal_record ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.meal_record_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notification_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notification_settings (
    id bigint NOT NULL,
    company_id bigint NOT NULL,
    email_enabled boolean DEFAULT false NOT NULL,
    slack_enabled boolean DEFAULT false NOT NULL,
    slack_webhook_url_encrypted character varying(1000),
    updated_at timestamp(6) without time zone
);


--
-- Name: notification_settings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notification_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: password_reset_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.password_reset_token (
    id bigint NOT NULL,
    app_user_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    token_hash character varying(64) NOT NULL,
    used_at timestamp(6) without time zone
);


--
-- Name: password_reset_token_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.password_reset_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.password_reset_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recipe; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recipe (
    id bigint NOT NULL,
    cook_minutes integer,
    cooking_method character varying(32),
    created_at timestamp(6) without time zone,
    difficulty integer,
    employee_id character varying(64) NOT NULL,
    equipment character varying(200),
    memo character varying(500),
    name character varying(200) NOT NULL,
    prep_minutes integer,
    reheat_method character varying(200),
    storage_days integer,
    storage_freezer boolean,
    storage_fridge boolean,
    updated_at timestamp(6) without time zone,
    calories integer,
    carbs_g double precision,
    fat_g double precision,
    protein_g double precision,
    salt_g double precision,
    CONSTRAINT recipe_cooking_method_check CHECK (((cooking_method)::text = ANY ((ARRAY['GRILL'::character varying, 'STIR_FRY'::character varying, 'SIMMER'::character varying, 'STEAM'::character varying, 'BOIL'::character varying, 'DEEP_FRY'::character varying, 'MICROWAVE'::character varying, 'RICE_COOKER'::character varying, 'TOSS'::character varying, 'RAW'::character varying, 'OTHER'::character varying])::text[])))
);


--
-- Name: recipe_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recipe ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recipe_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recipe_ingredient; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recipe_ingredient (
    id bigint NOT NULL,
    display_order integer NOT NULL,
    name character varying(100) NOT NULL,
    quantity double precision,
    recipe_id bigint NOT NULL,
    unit character varying(20)
);


--
-- Name: recipe_ingredient_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recipe_ingredient ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recipe_ingredient_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recipe_step; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recipe_step (
    id bigint NOT NULL,
    description character varying(500) NOT NULL,
    recipe_id bigint NOT NULL,
    step_no integer NOT NULL
);


--
-- Name: recipe_step_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recipe_step ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recipe_step_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schedule_event; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schedule_event (
    id bigint NOT NULL,
    category character varying(32) NOT NULL,
    employee_id character varying(64) NOT NULL,
    end_time time(6) without time zone,
    event_date date NOT NULL,
    memo character varying(255),
    start_time time(6) without time zone,
    title character varying(120) NOT NULL,
    company_id bigint,
    created_by_user_id bigint,
    department_id bigint,
    location character varying(255),
    schedule_type character varying(32),
    CONSTRAINT schedule_event_category_check CHECK (((category)::text = ANY ((ARRAY['WORK'::character varying, 'MEETING'::character varying, 'PRIVATE'::character varying, 'HEALTH'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT schedule_event_schedule_type_check CHECK (((schedule_type)::text = ANY ((ARRAY['PERSONAL'::character varying, 'DEPARTMENT'::character varying])::text[])))
);


--
-- Name: schedule_event_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.schedule_event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schedule_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: task; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.task (
    id bigint NOT NULL,
    assigned_user_id bigint NOT NULL,
    company_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by_user_id bigint NOT NULL,
    department_id bigint NOT NULL,
    description character varying(2000),
    due_date date,
    notes character varying(500),
    priority character varying(32) NOT NULL,
    start_date date,
    status character varying(32) NOT NULL,
    title character varying(120) NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT task_priority_check CHECK (((priority)::text = ANY ((ARRAY['HIGH'::character varying, 'MEDIUM'::character varying, 'LOW'::character varying])::text[]))),
    CONSTRAINT task_status_check CHECK (((status)::text = ANY ((ARRAY['UNRESOLVED'::character varying, 'IN_PROGRESS'::character varying, 'COMPLETED'::character varying])::text[])))
);


--
-- Name: task_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.task ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.task_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_food_preference; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_food_preference (
    id bigint NOT NULL,
    allergies character varying(500),
    budget_yen integer,
    cooking_level character varying(32),
    cooking_minutes integer,
    dietary_restrictions character varying(500),
    disliked_foods character varying(500),
    employee_id character varying(64) NOT NULL,
    favorite_foods character varying(500),
    self_cooked character varying(32),
    updated_at timestamp(6) without time zone,
    CONSTRAINT user_food_preference_cooking_level_check CHECK (((cooking_level)::text = ANY ((ARRAY['BEGINNER'::character varying, 'INTERMEDIATE'::character varying, 'ADVANCED'::character varying])::text[]))),
    CONSTRAINT user_food_preference_self_cooked_check CHECK (((self_cooked)::text = ANY ((ARRAY['SELF_COOK'::character varying, 'EATING_OUT'::character varying, 'EITHER'::character varying])::text[])))
);


--
-- Name: user_food_preference_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_food_preference ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_food_preference_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: account_security_log account_security_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_security_log
    ADD CONSTRAINT account_security_log_pkey PRIMARY KEY (id);


--
-- Name: ai_meal_suggestion_item ai_meal_suggestion_item_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_meal_suggestion_item
    ADD CONSTRAINT ai_meal_suggestion_item_pkey PRIMARY KEY (id);


--
-- Name: ai_meal_suggestion ai_meal_suggestion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_meal_suggestion
    ADD CONSTRAINT ai_meal_suggestion_pkey PRIMARY KEY (id);


--
-- Name: app_user app_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (id);


--
-- Name: attendance_audit attendance_audit_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance_audit
    ADD CONSTRAINT attendance_audit_pkey PRIMARY KEY (id);


--
-- Name: attendance_record attendance_record_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance_record
    ADD CONSTRAINT attendance_record_pkey PRIMARY KEY (id);


--
-- Name: company_holiday_rule company_holiday_rule_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_holiday_rule
    ADD CONSTRAINT company_holiday_rule_pkey PRIMARY KEY (id);


--
-- Name: company company_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company
    ADD CONSTRAINT company_pkey PRIMARY KEY (id);


--
-- Name: department department_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.department
    ADD CONSTRAINT department_pkey PRIMARY KEY (id);


--
-- Name: health_alert health_alert_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.health_alert
    ADD CONSTRAINT health_alert_pkey PRIMARY KEY (id);


--
-- Name: health_audit_log health_audit_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.health_audit_log
    ADD CONSTRAINT health_audit_log_pkey PRIMARY KEY (id);


--
-- Name: health_check health_check_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.health_check
    ADD CONSTRAINT health_check_pkey PRIMARY KEY (id);


--
-- Name: health_profile health_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.health_profile
    ADD CONSTRAINT health_profile_pkey PRIMARY KEY (id);


--
-- Name: health_record health_record_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.health_record
    ADD CONSTRAINT health_record_pkey PRIMARY KEY (id);


--
-- Name: holiday_override holiday_override_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.holiday_override
    ADD CONSTRAINT holiday_override_pkey PRIMARY KEY (id);


--
-- Name: meal_record meal_record_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meal_record
    ADD CONSTRAINT meal_record_pkey PRIMARY KEY (id);


--
-- Name: notification_settings notification_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_settings
    ADD CONSTRAINT notification_settings_pkey PRIMARY KEY (id);


--
-- Name: password_reset_token password_reset_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_token
    ADD CONSTRAINT password_reset_token_pkey PRIMARY KEY (id);


--
-- Name: recipe_ingredient recipe_ingredient_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipe_ingredient
    ADD CONSTRAINT recipe_ingredient_pkey PRIMARY KEY (id);


--
-- Name: recipe recipe_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipe
    ADD CONSTRAINT recipe_pkey PRIMARY KEY (id);


--
-- Name: recipe_step recipe_step_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipe_step
    ADD CONSTRAINT recipe_step_pkey PRIMARY KEY (id);


--
-- Name: schedule_event schedule_event_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schedule_event
    ADD CONSTRAINT schedule_event_pkey PRIMARY KEY (id);


--
-- Name: task task_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task
    ADD CONSTRAINT task_pkey PRIMARY KEY (id);


--
-- Name: health_profile uk8g90rw9sqbp7ir5l1pnga843n; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.health_profile
    ADD CONSTRAINT uk8g90rw9sqbp7ir5l1pnga843n UNIQUE (employee_id);


--
-- Name: user_food_preference uk9trsmobobumjasdi60w938ug1; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_food_preference
    ADD CONSTRAINT uk9trsmobobumjasdi60w938ug1 UNIQUE (employee_id);


--
-- Name: holiday_override ukaeehvi79mplvti5vjvx1br9rj; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.holiday_override
    ADD CONSTRAINT ukaeehvi79mplvti5vjvx1br9rj UNIQUE (holiday_date);


--
-- Name: password_reset_token ukanlf8vm14i1nn7pa6qlp0xa3w; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_token
    ADD CONSTRAINT ukanlf8vm14i1nn7pa6qlp0xa3w UNIQUE (token_hash);


--
-- Name: department ukbnau02s512rte2pat5egb04du; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.department
    ADD CONSTRAINT ukbnau02s512rte2pat5egb04du UNIQUE (company_id, name);


--
-- Name: notification_settings uke3m16l0pgo2jgb556ijp54oyh; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_settings
    ADD CONSTRAINT uke3m16l0pgo2jgb556ijp54oyh UNIQUE (company_id);


--
-- Name: app_user ukgimfa4mtkjn3sq26bd1sehg9m; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT ukgimfa4mtkjn3sq26bd1sehg9m UNIQUE (company_id, login_id);


--
-- Name: health_check ukhjg5c8gev2g2tw73o381drk8a; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.health_check
    ADD CONSTRAINT ukhjg5c8gev2g2tw73o381drk8a UNIQUE (employee_id, check_date);


--
-- Name: health_alert ukhwg8fe4erdnbbul55ea8dk0gj; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.health_alert
    ADD CONSTRAINT ukhwg8fe4erdnbbul55ea8dk0gj UNIQUE (employee_id, alert_type, triggered_date);


--
-- Name: company uki2jcjcejgnwuafxofwmgosd13; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company
    ADD CONSTRAINT uki2jcjcejgnwuafxofwmgosd13 UNIQUE (company_code);


--
-- Name: attendance_record ukj48d8tfe7te7b6ge5fkn8yckc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance_record
    ADD CONSTRAINT ukj48d8tfe7te7b6ge5fkn8yckc UNIQUE (employee_id, work_date);


--
-- Name: health_record ukq5tcyrsg0aukfnrxe4qr25plg; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.health_record
    ADD CONSTRAINT ukq5tcyrsg0aukfnrxe4qr25plg UNIQUE (employee_id, record_date);


--
-- Name: company_holiday_rule ukqn38ayc9jmabq5144r0yrtf5; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_holiday_rule
    ADD CONSTRAINT ukqn38ayc9jmabq5144r0yrtf5 UNIQUE (company_code);


--
-- Name: user_food_preference user_food_preference_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_food_preference
    ADD CONSTRAINT user_food_preference_pkey PRIMARY KEY (id);


--
-- Name: uq_meal_record_daily_type; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_meal_record_daily_type ON public.meal_record USING btree (employee_id, meal_date, meal_type) WHERE ((meal_type)::text <> 'SNACK'::text);


--
-- PostgreSQL database dump complete
--

