-- ==============================================================
-- V3: お知らせ機能の追加
--
-- 既存のtask(タスク管理)と同じ設計方針(状態・重要度をEnumで表現し、
-- company_id/department_idのFKカラムで会社・部署単位のアクセス制御を行う)に合わせて
-- announcement(お知らせ本体)・announcement_read(既読管理)の2テーブルを追加する。
--
-- 監査ログはaccount_security_logへ相乗りさせず、専用テーブル(announcement_audit_log)
-- として追加した。account_security_logのtarget_employee_id/target_nameは
-- 「操作対象がアカウント(人)であること」を前提にした列であり、お知らせ操作の対象は
-- 「コンテンツ(お知らせ1件)」であって人ではないため、無理に相乗りさせると意味の異なる
-- 列を使い回すことになる。health_audit_logがaccount_security_logと別テーブルに
-- 分離されているのと同じ考え方(ドメインが違えば監査ログテーブルも分離する)を踏襲した。
-- (AnnouncementAuditLogのjavadoc参照)
-- ==============================================================

--
-- Name: announcement; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.announcement (
    id bigint NOT NULL,
    company_id bigint NOT NULL,
    department_id bigint,
    title character varying(200) NOT NULL,
    body character varying(4000) NOT NULL,
    importance character varying(32) NOT NULL,
    created_by_user_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    published_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone,
    CONSTRAINT announcement_importance_check CHECK (((importance)::text = ANY ((ARRAY['NORMAL'::character varying, 'IMPORTANT'::character varying])::text[])))
);

ALTER TABLE public.announcement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.announcement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.announcement
    ADD CONSTRAINT announcement_pkey PRIMARY KEY (id);

--
-- Name: announcement_read; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.announcement_read (
    id bigint NOT NULL,
    announcement_id bigint NOT NULL,
    app_user_id bigint NOT NULL,
    read_at timestamp(6) without time zone NOT NULL
);

ALTER TABLE public.announcement_read ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.announcement_read_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.announcement_read
    ADD CONSTRAINT announcement_read_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.announcement_read
    ADD CONSTRAINT uk_announcement_read_announcement_user UNIQUE (announcement_id, app_user_id);

--
-- Name: announcement_audit_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.announcement_audit_log (
    id bigint NOT NULL,
    company_id bigint NOT NULL,
    announcement_id bigint NOT NULL,
    announcement_title character varying(200),
    action_type character varying(16) NOT NULL,
    performed_by_employee_id character varying(64) NOT NULL,
    performed_by_name character varying(100),
    occurred_at timestamp(6) without time zone NOT NULL
);

ALTER TABLE public.announcement_audit_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.announcement_audit_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.announcement_audit_log
    ADD CONSTRAINT announcement_audit_log_pkey PRIMARY KEY (id);
