-- ==============================================================
-- V4: 残業申請機能の追加
--
-- Announcement機能(V3)と同じ設計方針(状態をEnumで表現し、company_id/department_idの
-- FKカラムで会社・部署単位のアクセス制御を行う)に合わせて overtime_request(残業申請本体)・
-- overtime_request_audit_log(監査ログ)の2テーブルを追加する。
--
-- 事前申請制であり、承認された申請は「予定」データとして保持するのみ。AttendanceRecordの
-- 実績(実際の打刻から計算されるovertimeMinutes)は書き換えない(OvertimeRequestのjavadoc参照)。
-- 取り下げは専用のstatusを持たず、行そのものを削除して表現する(status列にWITHDRAWNは無い)。
-- ==============================================================

--
-- Name: overtime_request; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.overtime_request (
    id bigint NOT NULL,
    company_id bigint NOT NULL,
    department_id bigint,
    applicant_user_id bigint NOT NULL,
    target_date date NOT NULL,
    planned_minutes integer NOT NULL,
    reason character varying(500) NOT NULL,
    status character varying(16) NOT NULL,
    approver_user_id bigint,
    approved_at timestamp(6) without time zone,
    reject_reason character varying(500),
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    CONSTRAINT overtime_request_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);

ALTER TABLE public.overtime_request ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.overtime_request_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.overtime_request
    ADD CONSTRAINT overtime_request_pkey PRIMARY KEY (id);

--
-- Name: overtime_request_audit_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.overtime_request_audit_log (
    id bigint NOT NULL,
    overtime_request_id bigint NOT NULL,
    actor_user_id bigint NOT NULL,
    action_type character varying(16) NOT NULL,
    acted_at timestamp(6) without time zone NOT NULL
);

ALTER TABLE public.overtime_request_audit_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.overtime_request_audit_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.overtime_request_audit_log
    ADD CONSTRAINT overtime_request_audit_log_pkey PRIMARY KEY (id);
